#!/usr/bin/env python3
from pathlib import Path
import re

STACK=Path(__file__).resolve().parents[1]
ROOT=STACK.parent

required=[
    'README.md','LICENSE','docs/SECURITY.md','docs/SOURCES.md','docs/THIRD-PARTY-NOTICES.md',
    'docs/CONTRIBUTING.md','docs/CHANGELOG.md','docs/RELEASE.md','docs/SUPPORT.md','installer/install.ps1','installer/uninstall.ps1','installer/verify-release.ps1',
    '.gitattributes','.gitignore','.github/workflows/validate.yml','.github/PULL_REQUEST_TEMPLATE.md',
    'tools/New-SourceManifest.ps1',
]
for rel in required:
    assert (ROOT/rel).is_file(), f'missing public-release file: {rel}'

assert (STACK/'VERSION.txt').read_text().strip() in {'14.3.0','14.3.1','14.3.2','14.3.3','14.3.4','14.3.5','14.3.6','14.3.7','14.3.8','14.3.9','14.3.10','14.3.11','14.3.12','14.3.13','14.3.14','14.3.15','14.3.16','14.3.17','14.3.18','14.3.19','14.3.20','14.3.21','14.3.22','14.3.23','14.3.24','14.3.25','14.3.26','14.3.27','14.3.28','14.3.29','14.3.30','14.3.31','14.3.36','14.3.37','14.3.38','14.3.40','14.3.41','14.3.42','14.3.43','14.4.0','14.4.1','14.4.2'}

# A public LatticeVale source tree must not carry third-party installers/packages/images or generated bytecode.
banned={'.exe','.msi','.dll','.so','.deb','.rpm','.tar','.tgz','.gz','.zip','.7z','.bin','.jar','.pyc','.pyo'}
violations=[]
for p in ROOT.rglob('*'):
    if not p.is_file():
        continue
    n=p.name.lower()
    if any(n.endswith(s) for s in banned): violations.append(str(p.relative_to(ROOT)))
assert not violations, f'bundled binary/archive artifacts: {violations}'

ps=(STACK/'Install-LatticeVale.ps1').read_text(encoding='utf-8')
bootstrap=(STACK/'linux/bootstrap.sh').read_text(encoding='utf-8')
configure=(STACK/'stack/configure-stack.sh').read_text(encoding='utf-8')
readme=(ROOT/'README.md').read_text(encoding='utf-8')
sources=(ROOT/'docs/SOURCES.md').read_text(encoding='utf-8')
security=(ROOT/'docs/SECURITY.md').read_text(encoding='utf-8')
release_install=(ROOT/'installer/install.ps1').read_text(encoding='utf-8')
release_uninstall=(ROOT/'installer/uninstall.ps1').read_text(encoding='utf-8')
release_verify=(ROOT/'installer/verify-release.ps1').read_text(encoding='utf-8')
manifest_module=(ROOT/'tools/ReleaseManifest.ps1').read_text(encoding='utf-8')
manifest_generator=(ROOT/'tools/New-SourceManifest.ps1').read_text(encoding='utf-8')
ci=(ROOT/'.github/workflows/validate.yml').read_text(encoding='utf-8')

# Official/declared acquisition boundaries used by runtime code.
assert 'https://pkgs.tailscale.com/stable/tailscale-setup-latest.exe' in ps
assert 'Get-AuthenticodeSignature -LiteralPath $installer' in ps
assert "$signerSubject -notmatch '(?i)tailscale'" in ps
assert 'https://download.docker.com/linux/ubuntu/gpg' in bootstrap
assert 'URIs: https://download.docker.com/linux/ubuntu' in bootstrap
assert 'https://github.com/plastic-labs/honcho.git' in configure
assert 'Tailscale.Tailscale' in ps and 'Obsidian.Obsidian' in ps and 'Canonical.UbuntuProforWSL' in ps
assert '@tobilu/qmd@${QMD_VERSION}' in (STACK/'stack/Dockerfile.qmd').read_text(encoding='utf-8')
for expected in ('pkgs.tailscale.com','download.docker.com','plastic-labs/honcho','@tobilu/qmd@2.5.3'):
    assert expected in sources, f'SOURCES.md missing {expected}'

# The documented bypass is isolated to one spawned PowerShell process, not stored user/machine policy.
launch='powershell.exe -NoLogo -NoProfile -ExecutionPolicy Bypass -File .\\installer\\install.ps1'
assert launch in readme and launch in security
assert 'Set-ExecutionPolicy Bypass' not in readme
assert 'Set-ExecutionPolicy Bypass' not in security


# Manifest verification is exact and rejects path ambiguity on Windows.
for manifest_code in (manifest_module,):
    assert 'Unsafe/non-portable release path' in manifest_code
    assert 'Duplicate/case-colliding source-manifest entry' in manifest_code
    assert 'ReparsePoint' in manifest_code
    assert 'Source-manifest path escapes the release root' in manifest_code
assert 'Get-ChildItem -Path . -Recurse -File' in ci
assert "@('.ps1','.psm1','.psd1')" in ci
assert 'Windows PowerShell 5.1' in ci and 'PowerShell 7' in ci
assert 'non-ASCII byte' in ci
assert 'Assert-LatticeValePortableReleaseRelativePath' in manifest_generator
assert 'function Assert-PortableReleaseRelativePath' not in manifest_generator
assert 'Case-colliding release paths are not portable to Windows' in manifest_generator
assert 'Refusing to manifest reparse-point release item' in manifest_generator
assert 'WriteAllText($Manifest' in manifest_generator and '-join "`n"' in manifest_generator
assert 'Release tree must not contain reparse points' in manifest_module
assert '[IO.Path]::GetPathRoot($rootFull)' in manifest_module
assert 'drive-relative semantics' in manifest_module
assert "$segment.EndsWith('.')" in manifest_module
assert 'CON|PRN|AUX|NUL|COM[1-9]|LPT[1-9]' in manifest_module

# Exact-byte manifests require deterministic checkout bytes on Windows and Linux.
gitattributes=(ROOT/'.gitattributes').read_text(encoding='utf-8').lower()
assert 'eol=crlf' not in gitattributes, 'CRLF checkout rules invalidate exact-byte source manifests'
assert '* text=auto eol=lf' in gitattributes
assert '*.ps1 text eol=lf' in gitattributes and '*.txt text eol=lf' in gitattributes
text_ext={'.ps1','.txt','.cmd','.bat','.sh','.py','.md','.json','.yaml','.yml','.conf'}
for source_file in ROOT.rglob('*'):
    if not source_file.is_file() or '.git' in source_file.parts:
        continue
    if source_file.suffix.lower() in text_ext or source_file.name in {'.gitattributes','.gitignore'} or source_file.name.startswith('Dockerfile'):
        assert b'\r\n' not in source_file.read_bytes(), f'CRLF bytes remain in hashed source: {source_file.relative_to(ROOT)}'

# CI must not scan its own regex definition as a forbidden opaque command.
assert "--exclude='validate.yml'" in ci
assert 'Get-ChildItem -Path . -Recurse -File' in ci
assert "@('.ps1','.psm1','.psd1')" in ci
assert 'Windows PowerShell 5.1' in ci and 'PowerShell 7' in ci
assert 'non-ASCII byte' in ci
assert 'apt-get install -y jq' in ci
assert "-name '*.msi'" in ci and "-name '*.zip'" in ci and "-name '*.deb'" in ci

# Reviewable runtime code must not use opaque execution patterns.
runtime_text='\n'.join([
    (ROOT/'installer/install.ps1').read_text(encoding='utf-8'),
    (ROOT/'installer/uninstall.ps1').read_text(encoding='utf-8'),
    (STACK/'Uninstall-LatticeVale.ps1').read_text(encoding='utf-8'),
    (ROOT/'installer/verify-release.ps1').read_text(encoding='utf-8'), ps, bootstrap, configure,
    (STACK/'stack/manage.sh').read_text(encoding='utf-8'),
    (STACK/'windows/LatticeVale-WslNativeRelay.ps1').read_text(encoding='utf-8'),
    (STACK/'windows/LatticeVale-Shortcut.ps1').read_text(encoding='utf-8'),
])
for pattern in (r'EncodedCommand',r'FromBase64String',r'Invoke-Expression',r'(?i)\bcurl\b[^\n|]*\|\s*(?:ba)?sh\b'):
    assert not re.search(pattern,runtime_text), f'opaque execution pattern present: {pattern}'

print('V14.3.0 PUBLIC RELEASE FIXTURES: PASS')
